# Generated by Django 6.0.4 on 2026-05-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AddField(
            model_name='recette',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recettes/'),
        ),
    ]
