# Generated by Django 6.0.4 on 2026-05-02 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0002_alter_categorie_options_recette_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('unite', models.CharField(blank=True, help_text='ex: grammes, ml, cuillère', max_length=50)),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'verbose_name_plural': 'Ingrédients',
            },
        ),
        migrations.AddField(
            model_name='recette',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recettes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recette',
            name='ingredients_list',
            field=models.ManyToManyField(blank=True, related_name='recettes', to='recettes.ingredient'),
        ),
    ]
